### ISSUE TITLE
大神，能不能单独维护一下这个插件呢

### ISSUE THREAD

**Issue by Seifon** [shmy/flutter_dlan#1]
因为有用官方的video_player,所以想单独加一下这个插件

希望你能把这个插件独立出来

修复一下部分机型闪退的问题，谢谢了

**Comment by shmy** [comment]
这个就是单独的插件哦，https://github.com/shmy/flutter_ddplayer 这个是集成了官方video_player的，昨天修复了部分机型闪退


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Seifon** [comment]
> 这个就是单独的插件哦，https://github.com/shmy/flutter_ddplayer 这个是集成了官方video_player的，昨天修复了部分机型闪退
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

可是看提交记录，没有针对这个flutter_dlan插件，单独修复部分机型闪退的问题呀。

现在的情况是：有的机型打开投屏，会闪退。

希望能够对这个dlan的插件单独修复一下，谢谢了

**Comment by shmy** [comment]
提交了 你试试


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Seifon** [comment]
> 提交了 你试试
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

可以了，谢谢。希望以后大神能一直维护这个独立插件
